// ============================================================
// BUILDING DATA — BU TALBOT CAMPUS
// ============================================================
//
// >>> YOUR ACTION REQUIRED: <<<
// Walk each building and update this file with real data:
//   1. Measure corridor lengths (steps work — 1 step ≈ 0.75m)
//   2. Note every junction/turn/stairwell
//   3. Note room numbers and which waypoint they're nearest to
//   4. Measure northOffset with a compass app at each building
//
// ============================================================

const BUILDINGS = {
  // === POOLE HOUSE (P) ===
  P: {
    name: "Poole House",
    code: "P",
    lat: 50.7422,
    lng: -1.8945,
    northOffset: 0,
    floors: {
      G: {
        name: "Ground Floor",
        waypoints: [
          { id: "PG-ENTRANCE", x: 0, y: 0, label: "Main Entrance", isEntrance: true },
          { id: "PG-MAIN-W", x: 5, y: 0, label: "Main Corridor West" },
          { id: "PG-JUNC-W", x: 10, y: 0, label: "West Junction" },
          { id: "PG-STAIRS-W", x: 10, y: -8, label: "West Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "P1-STAIRS-W" } },
          { id: "PG-NORTH-W", x: 10, y: 8, label: "North Corridor West" },
          { id: "PG-MAIN-C", x: 18, y: 0, label: "Main Corridor Centre" },
          { id: "PG-JUNC-E", x: 26, y: 0, label: "East Junction" },
          { id: "PG-NORTH-E", x: 26, y: 8, label: "North Corridor East" },
          { id: "PG-SOUTH", x: 26, y: -8, label: "South Corridor" },
          { id: "PG-EAST", x: 34, y: 0, label: "East Wing" },
          { id: "PG-STAIRS-E", x: 34, y: -8, label: "East Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "P1-STAIRS-E" } },
        ],
        edges: [
          { from: "PG-ENTRANCE", to: "PG-MAIN-W", distance: 5 },
          { from: "PG-MAIN-W", to: "PG-JUNC-W", distance: 5 },
          { from: "PG-JUNC-W", to: "PG-STAIRS-W", distance: 8 },
          { from: "PG-JUNC-W", to: "PG-NORTH-W", distance: 8 },
          { from: "PG-JUNC-W", to: "PG-MAIN-C", distance: 8 },
          { from: "PG-MAIN-C", to: "PG-JUNC-E", distance: 8 },
          { from: "PG-JUNC-E", to: "PG-NORTH-E", distance: 8 },
          { from: "PG-JUNC-E", to: "PG-SOUTH", distance: 8 },
          { from: "PG-JUNC-E", to: "PG-EAST", distance: 8 },
          { from: "PG-EAST", to: "PG-STAIRS-E", distance: 8 },
          { from: "PG-SOUTH", to: "PG-STAIRS-E", distance: 8 },
        ],
        rooms: [
          { code: "PG01", name: "Room G01", waypointId: "PG-ENTRANCE", direction: "left" },
          { code: "PG02", name: "Room G02", waypointId: "PG-ENTRANCE", direction: "right" },
          { code: "PG03", name: "Room G03", waypointId: "PG-MAIN-W", direction: "left" },
          { code: "PG04", name: "Room G04", waypointId: "PG-MAIN-W", direction: "right" },
          { code: "PG05", name: "Room G05", waypointId: "PG-MAIN-W", direction: "left" },
          { code: "PG06", name: "Room G06", waypointId: "PG-MAIN-W", direction: "right" },
          { code: "PG07", name: "Room G07", waypointId: "PG-MAIN-W", direction: "left" },
          { code: "PG08", name: "Room G08", waypointId: "PG-JUNC-W", direction: "left" },
          { code: "PG09", name: "Room G09", waypointId: "PG-JUNC-W", direction: "right" },
          { code: "PG10", name: "Room G10", waypointId: "PG-JUNC-W", direction: "left" },
          { code: "PG11", name: "Room G11", waypointId: "PG-JUNC-W", direction: "right" },
          { code: "PG12", name: "Room G12", waypointId: "PG-JUNC-W", direction: "left" },
          { code: "PG13", name: "Room G13", waypointId: "PG-NORTH-W", direction: "left" },
          { code: "PG14", name: "Room G14", waypointId: "PG-NORTH-W", direction: "right" },
          { code: "PG15", name: "Room G15", waypointId: "PG-NORTH-W", direction: "left" },
          { code: "PG16", name: "Room G16", waypointId: "PG-NORTH-W", direction: "right" },
          { code: "PG17", name: "Room G17", waypointId: "PG-NORTH-W", direction: "left" },
          { code: "PG18", name: "Room G18", waypointId: "PG-STAIRS-W", direction: "left" },
          { code: "PG19", name: "Room G19", waypointId: "PG-STAIRS-W", direction: "right" },
          { code: "PG20", name: "Room G20", waypointId: "PG-STAIRS-W", direction: "left" },
          { code: "PG21", name: "Room G21", waypointId: "PG-MAIN-C", direction: "left" },
          { code: "PG22", name: "Room G22", waypointId: "PG-MAIN-C", direction: "right" },
          { code: "PG23", name: "Room G23", waypointId: "PG-MAIN-C", direction: "left" },
          { code: "PG24", name: "Room G24", waypointId: "PG-MAIN-C", direction: "right" },
          { code: "PG25", name: "Room G25", waypointId: "PG-MAIN-C", direction: "left" },
          { code: "PG26", name: "Room G26", waypointId: "PG-MAIN-C", direction: "right" },
          { code: "PG27", name: "Room G27", waypointId: "PG-JUNC-E", direction: "left" },
          { code: "PG28", name: "Room G28", waypointId: "PG-JUNC-E", direction: "right" },
          { code: "PG29", name: "Room G29", waypointId: "PG-JUNC-E", direction: "left" },
          { code: "PG30", name: "Room G30", waypointId: "PG-JUNC-E", direction: "right" },
          { code: "PG31", name: "Room G31", waypointId: "PG-NORTH-E", direction: "left" },
          { code: "PG32", name: "Room G32", waypointId: "PG-NORTH-E", direction: "right" },
          { code: "PG33", name: "Room G33", waypointId: "PG-NORTH-E", direction: "left" },
          { code: "PG34", name: "Room G34", waypointId: "PG-NORTH-E", direction: "right" },
          { code: "PG35", name: "Room G35", waypointId: "PG-NORTH-E", direction: "left" },
          { code: "PG36", name: "Room G36", waypointId: "PG-SOUTH", direction: "left" },
          { code: "PG37", name: "Room G37", waypointId: "PG-SOUTH", direction: "right" },
          { code: "PG38", name: "Room G38", waypointId: "PG-SOUTH", direction: "left" },
          { code: "PG39", name: "Room G39", waypointId: "PG-SOUTH", direction: "right" },
          { code: "PG40", name: "Room G40", waypointId: "PG-SOUTH", direction: "left" },
          { code: "PG41", name: "Room G41", waypointId: "PG-EAST", direction: "left" },
          { code: "PG42", name: "Room G42", waypointId: "PG-EAST", direction: "right" },
          { code: "PG43", name: "Room G43", waypointId: "PG-EAST", direction: "left" },
          { code: "PG44", name: "Room G44", waypointId: "PG-EAST", direction: "right" },
          { code: "PG45", name: "Room G45", waypointId: "PG-EAST", direction: "left" },
          { code: "PG46", name: "Room G46", waypointId: "PG-STAIRS-E", direction: "left" },
          { code: "PG47", name: "Room G47", waypointId: "PG-STAIRS-E", direction: "right" },
          { code: "PG48", name: "Room G48", waypointId: "PG-STAIRS-E", direction: "left" },
          { code: "PG49", name: "Room G49", waypointId: "PG-STAIRS-E", direction: "right" },
          { code: "PG50", name: "Room G50", waypointId: "PG-STAIRS-E", direction: "left" },
        ],
      },
      1: {
        name: "First Floor",
        waypoints: [
          { id: "P1-WEST", x: 0, y: 0, label: "West Wing" },
          { id: "P1-MAIN-W", x: 5, y: 0, label: "Main Corridor West" },
          { id: "P1-JUNC-W", x: 10, y: 0, label: "West Junction" },
          { id: "P1-STAIRS-W", x: 10, y: -8, label: "West Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "PG-STAIRS-W" } },
          { id: "P1-NORTH-W", x: 10, y: 8, label: "North Corridor West" },
          { id: "P1-MAIN-C", x: 18, y: 0, label: "Main Corridor Centre" },
          { id: "P1-JUNC-E", x: 26, y: 0, label: "East Junction" },
          { id: "P1-NORTH-E", x: 26, y: 8, label: "North Corridor East" },
          { id: "P1-SOUTH", x: 26, y: -8, label: "South Corridor" },
          { id: "P1-EAST", x: 34, y: 0, label: "East Wing" },
          { id: "P1-STAIRS-E", x: 34, y: -8, label: "East Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "PG-STAIRS-E" } },
        ],
        edges: [
          { from: "P1-WEST", to: "P1-MAIN-W", distance: 5 },
          { from: "P1-MAIN-W", to: "P1-JUNC-W", distance: 5 },
          { from: "P1-JUNC-W", to: "P1-STAIRS-W", distance: 8 },
          { from: "P1-JUNC-W", to: "P1-NORTH-W", distance: 8 },
          { from: "P1-JUNC-W", to: "P1-MAIN-C", distance: 8 },
          { from: "P1-MAIN-C", to: "P1-JUNC-E", distance: 8 },
          { from: "P1-JUNC-E", to: "P1-NORTH-E", distance: 8 },
          { from: "P1-JUNC-E", to: "P1-SOUTH", distance: 8 },
          { from: "P1-JUNC-E", to: "P1-EAST", distance: 8 },
          { from: "P1-EAST", to: "P1-STAIRS-E", distance: 8 },
          { from: "P1-SOUTH", to: "P1-STAIRS-E", distance: 8 },
        ],
        rooms: [
          { code: "P101", name: "Room 101", waypointId: "P1-WEST", direction: "left" },
          { code: "P102", name: "Room 102", waypointId: "P1-WEST", direction: "right" },
          { code: "P103", name: "Room 103", waypointId: "P1-MAIN-W", direction: "left" },
          { code: "P104", name: "Room 104", waypointId: "P1-MAIN-W", direction: "right" },
          { code: "P105", name: "Room 105", waypointId: "P1-MAIN-W", direction: "left" },
          { code: "P106", name: "Room 106", waypointId: "P1-MAIN-W", direction: "right" },
          { code: "P107", name: "Room 107", waypointId: "P1-MAIN-W", direction: "left" },
          { code: "P108", name: "Room 108", waypointId: "P1-JUNC-W", direction: "left" },
          { code: "P109", name: "Room 109", waypointId: "P1-JUNC-W", direction: "right" },
          { code: "P110", name: "Room 110", waypointId: "P1-JUNC-W", direction: "left" },
          { code: "P111", name: "Room 111", waypointId: "P1-JUNC-W", direction: "right" },
          { code: "P112", name: "Room 112", waypointId: "P1-JUNC-W", direction: "left" },
          { code: "P113", name: "Room 113", waypointId: "P1-NORTH-W", direction: "left" },
          { code: "P114", name: "Room 114", waypointId: "P1-NORTH-W", direction: "right" },
          { code: "P115", name: "Room 115", waypointId: "P1-NORTH-W", direction: "left" },
          { code: "P116", name: "Room 116", waypointId: "P1-NORTH-W", direction: "right" },
          { code: "P117", name: "Room 117", waypointId: "P1-NORTH-W", direction: "left" },
          { code: "P118", name: "Room 118", waypointId: "P1-STAIRS-W", direction: "left" },
          { code: "P119", name: "Room 119", waypointId: "P1-STAIRS-W", direction: "right" },
          { code: "P120", name: "Room 120", waypointId: "P1-STAIRS-W", direction: "left" },
          { code: "P121", name: "Room 121", waypointId: "P1-MAIN-C", direction: "left" },
          { code: "P122", name: "Room 122", waypointId: "P1-MAIN-C", direction: "right" },
          { code: "P123", name: "Room 123", waypointId: "P1-MAIN-C", direction: "left" },
          { code: "P124", name: "Room 124", waypointId: "P1-MAIN-C", direction: "right" },
          { code: "P125", name: "Room 125", waypointId: "P1-MAIN-C", direction: "left" },
          { code: "P126", name: "Room 126", waypointId: "P1-MAIN-C", direction: "right" },
          { code: "P127", name: "Room 127", waypointId: "P1-JUNC-E", direction: "left" },
          { code: "P128", name: "Room 128", waypointId: "P1-JUNC-E", direction: "right" },
          { code: "P129", name: "Room 129", waypointId: "P1-JUNC-E", direction: "left" },
          { code: "P130", name: "Room 130", waypointId: "P1-JUNC-E", direction: "right" },
          { code: "P131", name: "Room 131", waypointId: "P1-NORTH-E", direction: "left" },
          { code: "P132", name: "Room 132", waypointId: "P1-NORTH-E", direction: "right" },
          { code: "P133", name: "Room 133", waypointId: "P1-NORTH-E", direction: "left" },
          { code: "P134", name: "Room 134", waypointId: "P1-NORTH-E", direction: "right" },
          { code: "P135", name: "Room 135", waypointId: "P1-NORTH-E", direction: "left" },
          { code: "P136", name: "Room 136", waypointId: "P1-SOUTH", direction: "left" },
          { code: "P137", name: "Room 137", waypointId: "P1-SOUTH", direction: "right" },
          { code: "P138", name: "Room 138", waypointId: "P1-SOUTH", direction: "left" },
          { code: "P139", name: "Room 139", waypointId: "P1-SOUTH", direction: "right" },
          { code: "P140", name: "Room 140", waypointId: "P1-SOUTH", direction: "left" },
          { code: "P141", name: "Room 141", waypointId: "P1-EAST", direction: "left" },
          { code: "P142", name: "Room 142", waypointId: "P1-EAST", direction: "right" },
          { code: "P143", name: "Room 143", waypointId: "P1-EAST", direction: "left" },
          { code: "P144", name: "Room 144", waypointId: "P1-EAST", direction: "right" },
          { code: "P145", name: "Room 145", waypointId: "P1-EAST", direction: "left" },
          { code: "P146", name: "Room 146", waypointId: "P1-STAIRS-E", direction: "left" },
          { code: "P147", name: "Room 147", waypointId: "P1-STAIRS-E", direction: "right" },
          { code: "P148", name: "Room 148", waypointId: "P1-STAIRS-E", direction: "left" },
          { code: "P149", name: "Room 149", waypointId: "P1-STAIRS-E", direction: "right" },
          { code: "P150", name: "Room 150", waypointId: "P1-STAIRS-E", direction: "left" },
        ],
      },
      2: {
        name: "Second Floor",
        waypoints: [
          { id: "P2-WEST", x: 0, y: 0, label: "West Wing" },
          { id: "P2-MAIN-W", x: 5, y: 0, label: "Main Corridor West" },
          { id: "P2-JUNC-W", x: 10, y: 0, label: "West Junction" },
          { id: "P2-STAIRS-W", x: 10, y: -8, label: "West Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "P1-STAIRS-W" } },
          { id: "P2-NORTH-W", x: 10, y: 8, label: "North Corridor West" },
          { id: "P2-MAIN-C", x: 18, y: 0, label: "Main Corridor Centre" },
          { id: "P2-JUNC-E", x: 26, y: 0, label: "East Junction" },
          { id: "P2-NORTH-E", x: 26, y: 8, label: "North Corridor East" },
          { id: "P2-SOUTH", x: 26, y: -8, label: "South Corridor" },
          { id: "P2-EAST", x: 34, y: 0, label: "East Wing" },
          { id: "P2-STAIRS-E", x: 34, y: -8, label: "East Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "P1-STAIRS-E" } },
        ],
        edges: [
          { from: "P2-WEST", to: "P2-MAIN-W", distance: 5 },
          { from: "P2-MAIN-W", to: "P2-JUNC-W", distance: 5 },
          { from: "P2-JUNC-W", to: "P2-STAIRS-W", distance: 8 },
          { from: "P2-JUNC-W", to: "P2-NORTH-W", distance: 8 },
          { from: "P2-JUNC-W", to: "P2-MAIN-C", distance: 8 },
          { from: "P2-MAIN-C", to: "P2-JUNC-E", distance: 8 },
          { from: "P2-JUNC-E", to: "P2-NORTH-E", distance: 8 },
          { from: "P2-JUNC-E", to: "P2-SOUTH", distance: 8 },
          { from: "P2-JUNC-E", to: "P2-EAST", distance: 8 },
          { from: "P2-EAST", to: "P2-STAIRS-E", distance: 8 },
          { from: "P2-SOUTH", to: "P2-STAIRS-E", distance: 8 },
        ],
        rooms: [
          { code: "P201", name: "Room 201", waypointId: "P2-WEST", direction: "left" },
          { code: "P202", name: "Room 202", waypointId: "P2-WEST", direction: "right" },
          { code: "P203", name: "Room 203", waypointId: "P2-MAIN-W", direction: "left" },
          { code: "P204", name: "Room 204", waypointId: "P2-MAIN-W", direction: "right" },
          { code: "P205", name: "Room 205", waypointId: "P2-MAIN-W", direction: "left" },
          { code: "P206", name: "Room 206", waypointId: "P2-MAIN-W", direction: "right" },
          { code: "P207", name: "Room 207", waypointId: "P2-MAIN-W", direction: "left" },
          { code: "P208", name: "Room 208", waypointId: "P2-JUNC-W", direction: "left" },
          { code: "P209", name: "Room 209", waypointId: "P2-JUNC-W", direction: "right" },
          { code: "P210", name: "Room 210", waypointId: "P2-JUNC-W", direction: "left" },
          { code: "P211", name: "Room 211", waypointId: "P2-JUNC-W", direction: "right" },
          { code: "P212", name: "Room 212", waypointId: "P2-JUNC-W", direction: "left" },
          { code: "P213", name: "Room 213", waypointId: "P2-NORTH-W", direction: "left" },
          { code: "P214", name: "Room 214", waypointId: "P2-NORTH-W", direction: "right" },
          { code: "P215", name: "Room 215", waypointId: "P2-NORTH-W", direction: "left" },
          { code: "P216", name: "Room 216", waypointId: "P2-NORTH-W", direction: "right" },
          { code: "P217", name: "Room 217", waypointId: "P2-NORTH-W", direction: "left" },
          { code: "P218", name: "Room 218", waypointId: "P2-STAIRS-W", direction: "left" },
          { code: "P219", name: "Room 219", waypointId: "P2-STAIRS-W", direction: "right" },
          { code: "P220", name: "Room 220", waypointId: "P2-STAIRS-W", direction: "left" },
          { code: "P221", name: "Room 221", waypointId: "P2-MAIN-C", direction: "left" },
          { code: "P222", name: "Room 222", waypointId: "P2-MAIN-C", direction: "right" },
          { code: "P223", name: "Room 223", waypointId: "P2-MAIN-C", direction: "left" },
          { code: "P224", name: "Room 224", waypointId: "P2-MAIN-C", direction: "right" },
          { code: "P225", name: "Room 225", waypointId: "P2-MAIN-C", direction: "left" },
          { code: "P226", name: "Room 226", waypointId: "P2-MAIN-C", direction: "right" },
          { code: "P227", name: "Room 227", waypointId: "P2-JUNC-E", direction: "left" },
          { code: "P228", name: "Room 228", waypointId: "P2-JUNC-E", direction: "right" },
          { code: "P229", name: "Room 229", waypointId: "P2-JUNC-E", direction: "left" },
          { code: "P230", name: "Room 230", waypointId: "P2-JUNC-E", direction: "right" },
          { code: "P231", name: "Room 231", waypointId: "P2-NORTH-E", direction: "left" },
          { code: "P232", name: "Room 232", waypointId: "P2-NORTH-E", direction: "right" },
          { code: "P233", name: "Room 233", waypointId: "P2-NORTH-E", direction: "left" },
          { code: "P234", name: "Room 234", waypointId: "P2-NORTH-E", direction: "right" },
          { code: "P235", name: "Room 235", waypointId: "P2-NORTH-E", direction: "left" },
          { code: "P236", name: "Room 236", waypointId: "P2-SOUTH", direction: "left" },
          { code: "P237", name: "Room 237", waypointId: "P2-SOUTH", direction: "right" },
          { code: "P238", name: "Room 238", waypointId: "P2-SOUTH", direction: "left" },
          { code: "P239", name: "Room 239", waypointId: "P2-SOUTH", direction: "right" },
          { code: "P240", name: "Room 240", waypointId: "P2-SOUTH", direction: "left" },
          { code: "P241", name: "Room 241", waypointId: "P2-EAST", direction: "left" },
          { code: "P242", name: "Room 242", waypointId: "P2-EAST", direction: "right" },
          { code: "P243", name: "Room 243", waypointId: "P2-EAST", direction: "left" },
          { code: "P244", name: "Room 244", waypointId: "P2-EAST", direction: "right" },
          { code: "P245", name: "Room 245", waypointId: "P2-EAST", direction: "left" },
          { code: "P246", name: "Room 246", waypointId: "P2-STAIRS-E", direction: "left" },
          { code: "P247", name: "Room 247", waypointId: "P2-STAIRS-E", direction: "right" },
          { code: "P248", name: "Room 248", waypointId: "P2-STAIRS-E", direction: "left" },
          { code: "P249", name: "Room 249", waypointId: "P2-STAIRS-E", direction: "right" },
          { code: "P250", name: "Room 250", waypointId: "P2-STAIRS-E", direction: "left" },
        ],
      },
      3: {
        name: "Third Floor",
        waypoints: [
          { id: "P3-WEST", x: 0, y: 0, label: "West Wing" },
          { id: "P3-MAIN-W", x: 5, y: 0, label: "Main Corridor West" },
          { id: "P3-JUNC-W", x: 10, y: 0, label: "West Junction" },
          { id: "P3-STAIRS-W", x: 10, y: -8, label: "West Stairwell", isStairs: true, connectsTo: { floor: "2", waypointId: "P2-STAIRS-W" } },
          { id: "P3-NORTH-W", x: 10, y: 8, label: "North Corridor West" },
          { id: "P3-MAIN-C", x: 18, y: 0, label: "Main Corridor Centre" },
          { id: "P3-JUNC-E", x: 26, y: 0, label: "East Junction" },
          { id: "P3-NORTH-E", x: 26, y: 8, label: "North Corridor East" },
          { id: "P3-SOUTH", x: 26, y: -8, label: "South Corridor" },
          { id: "P3-EAST", x: 34, y: 0, label: "East Wing" },
          { id: "P3-STAIRS-E", x: 34, y: -8, label: "East Stairwell", isStairs: true, connectsTo: { floor: "2", waypointId: "P2-STAIRS-E" } },
        ],
        edges: [
          { from: "P3-WEST", to: "P3-MAIN-W", distance: 5 },
          { from: "P3-MAIN-W", to: "P3-JUNC-W", distance: 5 },
          { from: "P3-JUNC-W", to: "P3-STAIRS-W", distance: 8 },
          { from: "P3-JUNC-W", to: "P3-NORTH-W", distance: 8 },
          { from: "P3-JUNC-W", to: "P3-MAIN-C", distance: 8 },
          { from: "P3-MAIN-C", to: "P3-JUNC-E", distance: 8 },
          { from: "P3-JUNC-E", to: "P3-NORTH-E", distance: 8 },
          { from: "P3-JUNC-E", to: "P3-SOUTH", distance: 8 },
          { from: "P3-JUNC-E", to: "P3-EAST", distance: 8 },
          { from: "P3-EAST", to: "P3-STAIRS-E", distance: 8 },
          { from: "P3-SOUTH", to: "P3-STAIRS-E", distance: 8 },
        ],
        rooms: [
          { code: "P301", name: "Room 301", waypointId: "P3-WEST", direction: "left" },
          { code: "P302", name: "Room 302", waypointId: "P3-WEST", direction: "right" },
          { code: "P303", name: "Room 303", waypointId: "P3-MAIN-W", direction: "left" },
          { code: "P304", name: "Room 304", waypointId: "P3-MAIN-W", direction: "right" },
          { code: "P305", name: "Room 305", waypointId: "P3-MAIN-W", direction: "left" },
          { code: "P306", name: "Room 306", waypointId: "P3-MAIN-W", direction: "right" },
          { code: "P307", name: "Room 307", waypointId: "P3-MAIN-W", direction: "left" },
          { code: "P308", name: "Room 308", waypointId: "P3-JUNC-W", direction: "left" },
          { code: "P309", name: "Room 309", waypointId: "P3-JUNC-W", direction: "right" },
          { code: "P310", name: "Room 310", waypointId: "P3-JUNC-W", direction: "left" },
          { code: "P311", name: "Room 311", waypointId: "P3-JUNC-W", direction: "right" },
          { code: "P312", name: "Room 312", waypointId: "P3-JUNC-W", direction: "left" },
          { code: "P313", name: "Room 313", waypointId: "P3-NORTH-W", direction: "left" },
          { code: "P314", name: "Room 314", waypointId: "P3-NORTH-W", direction: "right" },
          { code: "P315", name: "Room 315", waypointId: "P3-NORTH-W", direction: "left" },
          { code: "P316", name: "Room 316", waypointId: "P3-NORTH-W", direction: "right" },
          { code: "P317", name: "Room 317", waypointId: "P3-NORTH-W", direction: "left" },
          { code: "P318", name: "Room 318", waypointId: "P3-STAIRS-W", direction: "left" },
          { code: "P319", name: "Room 319", waypointId: "P3-STAIRS-W", direction: "right" },
          { code: "P320", name: "Room 320", waypointId: "P3-STAIRS-W", direction: "left" },
          { code: "P321", name: "Room 321", waypointId: "P3-MAIN-C", direction: "left" },
          { code: "P322", name: "Room 322", waypointId: "P3-MAIN-C", direction: "right" },
          { code: "P323", name: "Room 323", waypointId: "P3-MAIN-C", direction: "left" },
          { code: "P324", name: "Room 324", waypointId: "P3-MAIN-C", direction: "right" },
          { code: "P325", name: "Room 325", waypointId: "P3-MAIN-C", direction: "left" },
          { code: "P326", name: "Room 326", waypointId: "P3-MAIN-C", direction: "right" },
          { code: "P327", name: "Room 327", waypointId: "P3-JUNC-E", direction: "left" },
          { code: "P328", name: "Room 328", waypointId: "P3-JUNC-E", direction: "right" },
          { code: "P329", name: "Room 329", waypointId: "P3-JUNC-E", direction: "left" },
          { code: "P330", name: "Room 330", waypointId: "P3-JUNC-E", direction: "right" },
          { code: "P331", name: "Room 331", waypointId: "P3-NORTH-E", direction: "left" },
          { code: "P332", name: "Room 332", waypointId: "P3-NORTH-E", direction: "right" },
          { code: "P333", name: "Room 333", waypointId: "P3-NORTH-E", direction: "left" },
          { code: "P334", name: "Room 334", waypointId: "P3-NORTH-E", direction: "right" },
          { code: "P335", name: "Room 335", waypointId: "P3-NORTH-E", direction: "left" },
          { code: "P336", name: "Room 336", waypointId: "P3-SOUTH", direction: "left" },
          { code: "P337", name: "Room 337", waypointId: "P3-SOUTH", direction: "right" },
          { code: "P338", name: "Room 338", waypointId: "P3-SOUTH", direction: "left" },
          { code: "P339", name: "Room 339", waypointId: "P3-SOUTH", direction: "right" },
          { code: "P340", name: "Room 340", waypointId: "P3-SOUTH", direction: "left" },
          { code: "P341", name: "Room 341", waypointId: "P3-EAST", direction: "left" },
          { code: "P342", name: "Room 342", waypointId: "P3-EAST", direction: "right" },
          { code: "P343", name: "Room 343", waypointId: "P3-EAST", direction: "left" },
          { code: "P344", name: "Room 344", waypointId: "P3-EAST", direction: "right" },
          { code: "P345", name: "Room 345", waypointId: "P3-EAST", direction: "left" },
          { code: "P346", name: "Room 346", waypointId: "P3-STAIRS-E", direction: "left" },
          { code: "P347", name: "Room 347", waypointId: "P3-STAIRS-E", direction: "right" },
          { code: "P348", name: "Room 348", waypointId: "P3-STAIRS-E", direction: "left" },
          { code: "P349", name: "Room 349", waypointId: "P3-STAIRS-E", direction: "right" },
          { code: "P350", name: "Room 350", waypointId: "P3-STAIRS-E", direction: "left" },
        ],
      },
      4: {
        name: "Fourth Floor",
        waypoints: [
          { id: "P4-WEST", x: 0, y: 0, label: "West Wing" },
          { id: "P4-MAIN-W", x: 5, y: 0, label: "Main Corridor West" },
          { id: "P4-JUNC-W", x: 10, y: 0, label: "West Junction" },
          { id: "P4-STAIRS-W", x: 10, y: -8, label: "West Stairwell", isStairs: true, connectsTo: { floor: "3", waypointId: "P3-STAIRS-W" } },
          { id: "P4-NORTH-W", x: 10, y: 8, label: "North Corridor West" },
          { id: "P4-MAIN-C", x: 18, y: 0, label: "Main Corridor Centre" },
          { id: "P4-JUNC-E", x: 26, y: 0, label: "East Junction" },
          { id: "P4-NORTH-E", x: 26, y: 8, label: "North Corridor East" },
          { id: "P4-SOUTH", x: 26, y: -8, label: "South Corridor" },
          { id: "P4-EAST", x: 34, y: 0, label: "East Wing" },
          { id: "P4-STAIRS-E", x: 34, y: -8, label: "East Stairwell", isStairs: true, connectsTo: { floor: "3", waypointId: "P3-STAIRS-E" } },
        ],
        edges: [
          { from: "P4-WEST", to: "P4-MAIN-W", distance: 5 },
          { from: "P4-MAIN-W", to: "P4-JUNC-W", distance: 5 },
          { from: "P4-JUNC-W", to: "P4-STAIRS-W", distance: 8 },
          { from: "P4-JUNC-W", to: "P4-NORTH-W", distance: 8 },
          { from: "P4-JUNC-W", to: "P4-MAIN-C", distance: 8 },
          { from: "P4-MAIN-C", to: "P4-JUNC-E", distance: 8 },
          { from: "P4-JUNC-E", to: "P4-NORTH-E", distance: 8 },
          { from: "P4-JUNC-E", to: "P4-SOUTH", distance: 8 },
          { from: "P4-JUNC-E", to: "P4-EAST", distance: 8 },
          { from: "P4-EAST", to: "P4-STAIRS-E", distance: 8 },
          { from: "P4-SOUTH", to: "P4-STAIRS-E", distance: 8 },
        ],
        rooms: [
          { code: "P401", name: "Room 401", waypointId: "P4-WEST", direction: "left" },
          { code: "P402", name: "Room 402", waypointId: "P4-WEST", direction: "right" },
          { code: "P403", name: "Room 403", waypointId: "P4-MAIN-W", direction: "left" },
          { code: "P404", name: "Room 404", waypointId: "P4-MAIN-W", direction: "right" },
          { code: "P405", name: "Room 405", waypointId: "P4-MAIN-W", direction: "left" },
          { code: "P406", name: "Room 406", waypointId: "P4-MAIN-W", direction: "right" },
          { code: "P407", name: "Room 407", waypointId: "P4-MAIN-W", direction: "left" },
          { code: "P408", name: "Room 408", waypointId: "P4-JUNC-W", direction: "left" },
          { code: "P409", name: "Room 409", waypointId: "P4-JUNC-W", direction: "right" },
          { code: "P410", name: "Room 410", waypointId: "P4-JUNC-W", direction: "left" },
          { code: "P411", name: "Room 411", waypointId: "P4-JUNC-W", direction: "right" },
          { code: "P412", name: "Room 412", waypointId: "P4-JUNC-W", direction: "left" },
          { code: "P413", name: "Room 413", waypointId: "P4-NORTH-W", direction: "left" },
          { code: "P414", name: "Room 414", waypointId: "P4-NORTH-W", direction: "right" },
          { code: "P415", name: "Room 415", waypointId: "P4-NORTH-W", direction: "left" },
          { code: "P416", name: "Room 416", waypointId: "P4-NORTH-W", direction: "right" },
          { code: "P417", name: "Room 417", waypointId: "P4-NORTH-W", direction: "left" },
          { code: "P418", name: "Room 418", waypointId: "P4-STAIRS-W", direction: "left" },
          { code: "P419", name: "Room 419", waypointId: "P4-STAIRS-W", direction: "right" },
          { code: "P420", name: "Room 420", waypointId: "P4-STAIRS-W", direction: "left" },
          { code: "P421", name: "Room 421", waypointId: "P4-MAIN-C", direction: "left" },
          { code: "P422", name: "Room 422", waypointId: "P4-MAIN-C", direction: "right" },
          { code: "P423", name: "Room 423", waypointId: "P4-MAIN-C", direction: "left" },
          { code: "P424", name: "Room 424", waypointId: "P4-MAIN-C", direction: "right" },
          { code: "P425", name: "Room 425", waypointId: "P4-MAIN-C", direction: "left" },
          { code: "P426", name: "Room 426", waypointId: "P4-MAIN-C", direction: "right" },
          { code: "P427", name: "Room 427", waypointId: "P4-JUNC-E", direction: "left" },
          { code: "P428", name: "Room 428", waypointId: "P4-JUNC-E", direction: "right" },
          { code: "P429", name: "Room 429", waypointId: "P4-JUNC-E", direction: "left" },
          { code: "P430", name: "Room 430", waypointId: "P4-JUNC-E", direction: "right" },
          { code: "P431", name: "Room 431", waypointId: "P4-NORTH-E", direction: "left" },
          { code: "P432", name: "Room 432", waypointId: "P4-NORTH-E", direction: "right" },
          { code: "P433", name: "Room 433", waypointId: "P4-NORTH-E", direction: "left" },
          { code: "P434", name: "Room 434", waypointId: "P4-NORTH-E", direction: "right" },
          { code: "P435", name: "Room 435", waypointId: "P4-NORTH-E", direction: "left" },
          { code: "P436", name: "Room 436", waypointId: "P4-SOUTH", direction: "left" },
          { code: "P437", name: "Room 437", waypointId: "P4-SOUTH", direction: "right" },
          { code: "P438", name: "Room 438", waypointId: "P4-SOUTH", direction: "left" },
          { code: "P439", name: "Room 439", waypointId: "P4-SOUTH", direction: "right" },
          { code: "P440", name: "Room 440", waypointId: "P4-SOUTH", direction: "left" },
          { code: "P441", name: "Room 441", waypointId: "P4-EAST", direction: "left" },
          { code: "P442", name: "Room 442", waypointId: "P4-EAST", direction: "right" },
          { code: "P443", name: "Room 443", waypointId: "P4-EAST", direction: "left" },
          { code: "P444", name: "Room 444", waypointId: "P4-EAST", direction: "right" },
          { code: "P445", name: "Room 445", waypointId: "P4-EAST", direction: "left" },
          { code: "P446", name: "Room 446", waypointId: "P4-STAIRS-E", direction: "left" },
          { code: "P447", name: "Room 447", waypointId: "P4-STAIRS-E", direction: "right" },
          { code: "P448", name: "Room 448", waypointId: "P4-STAIRS-E", direction: "left" },
          { code: "P449", name: "Room 449", waypointId: "P4-STAIRS-E", direction: "right" },
          { code: "P450", name: "Room 450", waypointId: "P4-STAIRS-E", direction: "left" },
        ],
      },
      5: {
        name: "Fifth Floor",
        waypoints: [
          { id: "P5-WEST", x: 0, y: 0, label: "West Wing" },
          { id: "P5-MAIN-W", x: 5, y: 0, label: "Main Corridor West" },
          { id: "P5-JUNC-W", x: 10, y: 0, label: "West Junction" },
          { id: "P5-STAIRS-W", x: 10, y: -8, label: "West Stairwell", isStairs: true, connectsTo: { floor: "4", waypointId: "P4-STAIRS-W" } },
          { id: "P5-NORTH-W", x: 10, y: 8, label: "North Corridor West" },
          { id: "P5-MAIN-C", x: 18, y: 0, label: "Main Corridor Centre" },
          { id: "P5-JUNC-E", x: 26, y: 0, label: "East Junction" },
          { id: "P5-NORTH-E", x: 26, y: 8, label: "North Corridor East" },
          { id: "P5-SOUTH", x: 26, y: -8, label: "South Corridor" },
          { id: "P5-EAST", x: 34, y: 0, label: "East Wing" },
          { id: "P5-STAIRS-E", x: 34, y: -8, label: "East Stairwell", isStairs: true, connectsTo: { floor: "4", waypointId: "P4-STAIRS-E" } },
        ],
        edges: [
          { from: "P5-WEST", to: "P5-MAIN-W", distance: 5 },
          { from: "P5-MAIN-W", to: "P5-JUNC-W", distance: 5 },
          { from: "P5-JUNC-W", to: "P5-STAIRS-W", distance: 8 },
          { from: "P5-JUNC-W", to: "P5-NORTH-W", distance: 8 },
          { from: "P5-JUNC-W", to: "P5-MAIN-C", distance: 8 },
          { from: "P5-MAIN-C", to: "P5-JUNC-E", distance: 8 },
          { from: "P5-JUNC-E", to: "P5-NORTH-E", distance: 8 },
          { from: "P5-JUNC-E", to: "P5-SOUTH", distance: 8 },
          { from: "P5-JUNC-E", to: "P5-EAST", distance: 8 },
          { from: "P5-EAST", to: "P5-STAIRS-E", distance: 8 },
          { from: "P5-SOUTH", to: "P5-STAIRS-E", distance: 8 },
        ],
        rooms: [
          { code: "P501", name: "Room 501", waypointId: "P5-WEST", direction: "left" },
          { code: "P502", name: "Room 502", waypointId: "P5-WEST", direction: "right" },
          { code: "P503", name: "Room 503", waypointId: "P5-MAIN-W", direction: "left" },
          { code: "P504", name: "Room 504", waypointId: "P5-MAIN-W", direction: "right" },
          { code: "P505", name: "Room 505", waypointId: "P5-MAIN-W", direction: "left" },
          { code: "P506", name: "Room 506", waypointId: "P5-MAIN-W", direction: "right" },
          { code: "P507", name: "Room 507", waypointId: "P5-MAIN-W", direction: "left" },
          { code: "P508", name: "Room 508", waypointId: "P5-JUNC-W", direction: "left" },
          { code: "P509", name: "Room 509", waypointId: "P5-JUNC-W", direction: "right" },
          { code: "P510", name: "Room 510", waypointId: "P5-JUNC-W", direction: "left" },
          { code: "P511", name: "Room 511", waypointId: "P5-JUNC-W", direction: "right" },
          { code: "P512", name: "Room 512", waypointId: "P5-JUNC-W", direction: "left" },
          { code: "P513", name: "Room 513", waypointId: "P5-NORTH-W", direction: "left" },
          { code: "P514", name: "Room 514", waypointId: "P5-NORTH-W", direction: "right" },
          { code: "P515", name: "Room 515", waypointId: "P5-NORTH-W", direction: "left" },
          { code: "P516", name: "Room 516", waypointId: "P5-NORTH-W", direction: "right" },
          { code: "P517", name: "Room 517", waypointId: "P5-NORTH-W", direction: "left" },
          { code: "P518", name: "Room 518", waypointId: "P5-STAIRS-W", direction: "left" },
          { code: "P519", name: "Room 519", waypointId: "P5-STAIRS-W", direction: "right" },
          { code: "P520", name: "Room 520", waypointId: "P5-STAIRS-W", direction: "left" },
          { code: "P521", name: "Room 521", waypointId: "P5-MAIN-C", direction: "left" },
          { code: "P522", name: "Room 522", waypointId: "P5-MAIN-C", direction: "right" },
          { code: "P523", name: "Room 523", waypointId: "P5-MAIN-C", direction: "left" },
          { code: "P524", name: "Room 524", waypointId: "P5-MAIN-C", direction: "right" },
          { code: "P525", name: "Room 525", waypointId: "P5-MAIN-C", direction: "left" },
          { code: "P526", name: "Room 526", waypointId: "P5-MAIN-C", direction: "right" },
          { code: "P527", name: "Room 527", waypointId: "P5-JUNC-E", direction: "left" },
          { code: "P528", name: "Room 528", waypointId: "P5-JUNC-E", direction: "right" },
          { code: "P529", name: "Room 529", waypointId: "P5-JUNC-E", direction: "left" },
          { code: "P530", name: "Room 530", waypointId: "P5-JUNC-E", direction: "right" },
          { code: "P531", name: "Room 531", waypointId: "P5-NORTH-E", direction: "left" },
          { code: "P532", name: "Room 532", waypointId: "P5-NORTH-E", direction: "right" },
          { code: "P533", name: "Room 533", waypointId: "P5-NORTH-E", direction: "left" },
          { code: "P534", name: "Room 534", waypointId: "P5-NORTH-E", direction: "right" },
          { code: "P535", name: "Room 535", waypointId: "P5-NORTH-E", direction: "left" },
          { code: "P536", name: "Room 536", waypointId: "P5-SOUTH", direction: "left" },
          { code: "P537", name: "Room 537", waypointId: "P5-SOUTH", direction: "right" },
          { code: "P538", name: "Room 538", waypointId: "P5-SOUTH", direction: "left" },
          { code: "P539", name: "Room 539", waypointId: "P5-SOUTH", direction: "right" },
          { code: "P540", name: "Room 540", waypointId: "P5-SOUTH", direction: "left" },
          { code: "P541", name: "Room 541", waypointId: "P5-EAST", direction: "left" },
          { code: "P542", name: "Room 542", waypointId: "P5-EAST", direction: "right" },
          { code: "P543", name: "Room 543", waypointId: "P5-EAST", direction: "left" },
          { code: "P544", name: "Room 544", waypointId: "P5-EAST", direction: "right" },
          { code: "P545", name: "Room 545", waypointId: "P5-EAST", direction: "left" },
          { code: "P546", name: "Room 546", waypointId: "P5-STAIRS-E", direction: "left" },
          { code: "P547", name: "Room 547", waypointId: "P5-STAIRS-E", direction: "right" },
          { code: "P548", name: "Room 548", waypointId: "P5-STAIRS-E", direction: "left" },
          { code: "P549", name: "Room 549", waypointId: "P5-STAIRS-E", direction: "right" },
          { code: "P550", name: "Room 550", waypointId: "P5-STAIRS-E", direction: "left" },
        ],
      },
      6: {
        name: "Sixth Floor",
        waypoints: [
          { id: "P6-WEST", x: 0, y: 0, label: "West Wing" },
          { id: "P6-MAIN-W", x: 5, y: 0, label: "Main Corridor West" },
          { id: "P6-JUNC-W", x: 10, y: 0, label: "West Junction" },
          { id: "P6-STAIRS-W", x: 10, y: -8, label: "West Stairwell", isStairs: true, connectsTo: { floor: "5", waypointId: "P5-STAIRS-W" } },
          { id: "P6-NORTH-W", x: 10, y: 8, label: "North Corridor West" },
          { id: "P6-MAIN-C", x: 18, y: 0, label: "Main Corridor Centre" },
          { id: "P6-JUNC-E", x: 26, y: 0, label: "East Junction" },
          { id: "P6-NORTH-E", x: 26, y: 8, label: "North Corridor East" },
          { id: "P6-SOUTH", x: 26, y: -8, label: "South Corridor" },
          { id: "P6-EAST", x: 34, y: 0, label: "East Wing" },
          { id: "P6-STAIRS-E", x: 34, y: -8, label: "East Stairwell", isStairs: true, connectsTo: { floor: "5", waypointId: "P5-STAIRS-E" } },
        ],
        edges: [
          { from: "P6-WEST", to: "P6-MAIN-W", distance: 5 },
          { from: "P6-MAIN-W", to: "P6-JUNC-W", distance: 5 },
          { from: "P6-JUNC-W", to: "P6-STAIRS-W", distance: 8 },
          { from: "P6-JUNC-W", to: "P6-NORTH-W", distance: 8 },
          { from: "P6-JUNC-W", to: "P6-MAIN-C", distance: 8 },
          { from: "P6-MAIN-C", to: "P6-JUNC-E", distance: 8 },
          { from: "P6-JUNC-E", to: "P6-NORTH-E", distance: 8 },
          { from: "P6-JUNC-E", to: "P6-SOUTH", distance: 8 },
          { from: "P6-JUNC-E", to: "P6-EAST", distance: 8 },
          { from: "P6-EAST", to: "P6-STAIRS-E", distance: 8 },
          { from: "P6-SOUTH", to: "P6-STAIRS-E", distance: 8 },
        ],
        rooms: [
          { code: "P601", name: "Room 601", waypointId: "P6-WEST", direction: "left" },
          { code: "P602", name: "Room 602", waypointId: "P6-WEST", direction: "right" },
          { code: "P603", name: "Room 603", waypointId: "P6-MAIN-W", direction: "left" },
          { code: "P604", name: "Room 604", waypointId: "P6-MAIN-W", direction: "right" },
          { code: "P605", name: "Room 605", waypointId: "P6-MAIN-W", direction: "left" },
          { code: "P606", name: "Room 606", waypointId: "P6-MAIN-W", direction: "right" },
          { code: "P607", name: "Room 607", waypointId: "P6-MAIN-W", direction: "left" },
          { code: "P608", name: "Room 608", waypointId: "P6-JUNC-W", direction: "left" },
          { code: "P609", name: "Room 609", waypointId: "P6-JUNC-W", direction: "right" },
          { code: "P610", name: "Room 610", waypointId: "P6-JUNC-W", direction: "left" },
          { code: "P611", name: "Room 611", waypointId: "P6-JUNC-W", direction: "right" },
          { code: "P612", name: "Room 612", waypointId: "P6-JUNC-W", direction: "left" },
          { code: "P613", name: "Room 613", waypointId: "P6-NORTH-W", direction: "left" },
          { code: "P614", name: "Room 614", waypointId: "P6-NORTH-W", direction: "right" },
          { code: "P615", name: "Room 615", waypointId: "P6-NORTH-W", direction: "left" },
          { code: "P616", name: "Room 616", waypointId: "P6-NORTH-W", direction: "right" },
          { code: "P617", name: "Room 617", waypointId: "P6-NORTH-W", direction: "left" },
          { code: "P618", name: "Room 618", waypointId: "P6-STAIRS-W", direction: "left" },
          { code: "P619", name: "Room 619", waypointId: "P6-STAIRS-W", direction: "right" },
          { code: "P620", name: "Room 620", waypointId: "P6-STAIRS-W", direction: "left" },
          { code: "P621", name: "Room 621", waypointId: "P6-MAIN-C", direction: "left" },
          { code: "P622", name: "Room 622", waypointId: "P6-MAIN-C", direction: "right" },
          { code: "P623", name: "Room 623", waypointId: "P6-MAIN-C", direction: "left" },
          { code: "P624", name: "Room 624", waypointId: "P6-MAIN-C", direction: "right" },
          { code: "P625", name: "Room 625", waypointId: "P6-MAIN-C", direction: "left" },
          { code: "P626", name: "Room 626", waypointId: "P6-MAIN-C", direction: "right" },
          { code: "P627", name: "Room 627", waypointId: "P6-JUNC-E", direction: "left" },
          { code: "P628", name: "Room 628", waypointId: "P6-JUNC-E", direction: "right" },
          { code: "P629", name: "Room 629", waypointId: "P6-JUNC-E", direction: "left" },
          { code: "P630", name: "Room 630", waypointId: "P6-JUNC-E", direction: "right" },
          { code: "P631", name: "Room 631", waypointId: "P6-NORTH-E", direction: "left" },
          { code: "P632", name: "Room 632", waypointId: "P6-NORTH-E", direction: "right" },
          { code: "P633", name: "Room 633", waypointId: "P6-NORTH-E", direction: "left" },
          { code: "P634", name: "Room 634", waypointId: "P6-NORTH-E", direction: "right" },
          { code: "P635", name: "Room 635", waypointId: "P6-NORTH-E", direction: "left" },
          { code: "P636", name: "Room 636", waypointId: "P6-SOUTH", direction: "left" },
          { code: "P637", name: "Room 637", waypointId: "P6-SOUTH", direction: "right" },
          { code: "P638", name: "Room 638", waypointId: "P6-SOUTH", direction: "left" },
          { code: "P639", name: "Room 639", waypointId: "P6-SOUTH", direction: "right" },
          { code: "P640", name: "Room 640", waypointId: "P6-SOUTH", direction: "left" },
          { code: "P641", name: "Room 641", waypointId: "P6-EAST", direction: "left" },
          { code: "P642", name: "Room 642", waypointId: "P6-EAST", direction: "right" },
          { code: "P643", name: "Room 643", waypointId: "P6-EAST", direction: "left" },
          { code: "P644", name: "Room 644", waypointId: "P6-EAST", direction: "right" },
          { code: "P645", name: "Room 645", waypointId: "P6-EAST", direction: "left" },
          { code: "P646", name: "Room 646", waypointId: "P6-STAIRS-E", direction: "left" },
          { code: "P647", name: "Room 647", waypointId: "P6-STAIRS-E", direction: "right" },
          { code: "P648", name: "Room 648", waypointId: "P6-STAIRS-E", direction: "left" },
          { code: "P649", name: "Room 649", waypointId: "P6-STAIRS-E", direction: "right" },
          { code: "P650", name: "Room 650", waypointId: "P6-STAIRS-E", direction: "left" },
        ],
      },
    },
  },

  // === FUSION BUILDING (F) ===
  F: {
    name: "Fusion Building",
    code: "F",
    lat: 50.7418,
    lng: -1.8920,
    northOffset: 0,
    floors: {
      G: {
        name: "Ground Floor",
        waypoints: [
          { id: "FG-ENTRANCE", x: 0, y: 0, label: "Main Entrance", isEntrance: true },
          { id: "FG-LOBBY", x: 5, y: 0, label: "Lobby" },
          { id: "FG-JUNC1", x: 10, y: 0, label: "Central Junction" },
          { id: "FG-CORR-N", x: 10, y: 8, label: "North Wing" },
          { id: "FG-CORR-S", x: 10, y: -8, label: "South Wing" },
          { id: "FG-STAIRS1", x: 15, y: 0, label: "Main Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "F1-STAIRS1" } },
        ],
        edges: [
          { from: "FG-ENTRANCE", to: "FG-LOBBY", distance: 5 },
          { from: "FG-LOBBY", to: "FG-JUNC1", distance: 5 },
          { from: "FG-JUNC1", to: "FG-CORR-N", distance: 8 },
          { from: "FG-JUNC1", to: "FG-CORR-S", distance: 8 },
          { from: "FG-JUNC1", to: "FG-STAIRS1", distance: 5 },
        ],
        rooms: [
          { code: "FG01", name: "Reception", waypointId: "FG-LOBBY", direction: "right" },
          { code: "FG10", name: "Cafe", waypointId: "FG-JUNC1", direction: "left" },
          { code: "FG20", name: "Lab A", waypointId: "FG-CORR-N", direction: "left" },
          { code: "FG21", name: "Lab B", waypointId: "FG-CORR-N", direction: "right" },
          { code: "FG30", name: "Lecture Theatre", waypointId: "FG-CORR-S", direction: "right" },
        ],
      },
      1: {
        name: "First Floor",
        waypoints: [
          { id: "F1-STAIRS1", x: 15, y: 0, label: "Main Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "FG-STAIRS1" } },
          { id: "F1-CORR1", x: 10, y: 0, label: "Central Corridor" },
          { id: "F1-CORR-N", x: 10, y: 8, label: "North Wing" },
          { id: "F1-CORR-S", x: 10, y: -8, label: "South Wing" },
          { id: "F1-STAIRS2", x: 5, y: 0, label: "West Stairwell", isStairs: true, connectsTo: { floor: "2", waypointId: "F2-STAIRS2" } },
        ],
        edges: [
          { from: "F1-STAIRS1", to: "F1-CORR1", distance: 5 },
          { from: "F1-CORR1", to: "F1-CORR-N", distance: 8 },
          { from: "F1-CORR1", to: "F1-CORR-S", distance: 8 },
          { from: "F1-CORR1", to: "F1-STAIRS2", distance: 5 },
        ],
        rooms: [
          { code: "F101", name: "Study Room 1", waypointId: "F1-CORR1", direction: "left" },
          { code: "F110", name: "Library", waypointId: "F1-CORR-N", direction: "right" },
          { code: "F120", name: "Computer Lab", waypointId: "F1-CORR-S", direction: "left" },
        ],
      },
      2: {
        name: "Second Floor",
        waypoints: [
          { id: "F2-STAIRS2", x: 5, y: 0, label: "West Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "F1-STAIRS2" } },
          { id: "F2-CORR1", x: 10, y: 0, label: "Main Corridor" },
          { id: "F2-CORR2", x: 15, y: 0, label: "East Corridor" },
          { id: "F2-CORR-N", x: 10, y: 6, label: "North Side" },
        ],
        edges: [
          { from: "F2-STAIRS2", to: "F2-CORR1", distance: 5 },
          { from: "F2-CORR1", to: "F2-CORR2", distance: 5 },
          { from: "F2-CORR1", to: "F2-CORR-N", distance: 6 },
        ],
        rooms: [
          { code: "F201", name: "Seminar Room", waypointId: "F2-CORR1", direction: "right" },
          { code: "F234", name: "Design Studio", waypointId: "F2-CORR2", direction: "left" },
          { code: "F240", name: "Office 240", waypointId: "F2-CORR-N", direction: "right" },
        ],
      },
    },
  },

  // === KIMMERIDGE HOUSE (K) ===
  K: {
    name: "Kimmeridge House",
    code: "K",
    lat: 50.7432,
    lng: -1.8942,
    northOffset: 0,
    floors: {
      G: {
        name: "Ground Floor",
        waypoints: [
          { id: "KG-ENTRANCE", x: 0, y: 0, label: "Main Entrance", isEntrance: true },
          { id: "KG-CORR1", x: 8, y: 0, label: "Main Corridor" },
          { id: "KG-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "K1-STAIRS1" } },
        ],
        edges: [
          { from: "KG-ENTRANCE", to: "KG-CORR1", distance: 8 },
          { from: "KG-CORR1", to: "KG-STAIRS1", distance: 7 },
        ],
        rooms: [],
      },
      1: {
        name: "First Floor",
        waypoints: [
          { id: "K1-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "KG-STAIRS1" } },
          { id: "K1-CORR1", x: 8, y: 0, label: "Main Corridor" },
        ],
        edges: [
          { from: "K1-STAIRS1", to: "K1-CORR1", distance: 7 },
        ],
        rooms: [],
      },
    },
  },

  // === DORSET HOUSE (D) ===
  D: {
    name: "Dorset House",
    code: "D",
    lat: 50.7430,
    lng: -1.8928,
    northOffset: 0,
    floors: {
      G: {
        name: "Ground Floor",
        waypoints: [
          { id: "DG-ENTRANCE", x: 0, y: 0, label: "Main Entrance", isEntrance: true },
          { id: "DG-CORR1", x: 8, y: 0, label: "Main Corridor" },
          { id: "DG-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "D1-STAIRS1" } },
        ],
        edges: [
          { from: "DG-ENTRANCE", to: "DG-CORR1", distance: 8 },
          { from: "DG-CORR1", to: "DG-STAIRS1", distance: 7 },
        ],
        rooms: [],
      },
      1: {
        name: "First Floor",
        waypoints: [
          { id: "D1-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "DG-STAIRS1" } },
          { id: "D1-CORR1", x: 8, y: 0, label: "Main Corridor" },
        ],
        edges: [
          { from: "D1-STAIRS1", to: "D1-CORR1", distance: 7 },
        ],
        rooms: [],
      },
    },
  },

  // === CHRISTCHURCH HOUSE (C) ===
  C: {
    name: "Christchurch House",
    code: "C",
    lat: 50.7428,
    lng: -1.8908,
    northOffset: 0,
    floors: {
      G: {
        name: "Ground Floor",
        waypoints: [
          { id: "CG-ENTRANCE", x: 0, y: 0, label: "Main Entrance", isEntrance: true },
          { id: "CG-CORR1", x: 8, y: 0, label: "Main Corridor" },
          { id: "CG-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "C1-STAIRS1" } },
        ],
        edges: [
          { from: "CG-ENTRANCE", to: "CG-CORR1", distance: 8 },
          { from: "CG-CORR1", to: "CG-STAIRS1", distance: 7 },
        ],
        rooms: [],
      },
      1: {
        name: "First Floor",
        waypoints: [
          { id: "C1-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "CG-STAIRS1" } },
          { id: "C1-CORR1", x: 8, y: 0, label: "Main Corridor" },
        ],
        edges: [
          { from: "C1-STAIRS1", to: "C1-CORR1", distance: 7 },
        ],
        rooms: [],
      },
    },
  },

  // === WEYMOUTH HOUSE (W) ===
  W: {
    name: "Weymouth House",
    code: "W",
    lat: 50.7426,
    lng: -1.8922,
    northOffset: 0,
    floors: {
      G: {
        name: "Ground Floor",
        waypoints: [
          { id: "WG-ENTRANCE", x: 0, y: 0, label: "Main Entrance", isEntrance: true },
          { id: "WG-CORR1", x: 8, y: 0, label: "Main Corridor" },
          { id: "WG-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "W1-STAIRS1" } },
        ],
        edges: [
          { from: "WG-ENTRANCE", to: "WG-CORR1", distance: 8 },
          { from: "WG-CORR1", to: "WG-STAIRS1", distance: 7 },
        ],
        rooms: [],
      },
      1: {
        name: "First Floor",
        waypoints: [
          { id: "W1-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "WG-STAIRS1" } },
          { id: "W1-CORR1", x: 8, y: 0, label: "Main Corridor" },
        ],
        edges: [
          { from: "W1-STAIRS1", to: "W1-CORR1", distance: 7 },
        ],
        rooms: [],
      },
    },
  },

  // === JURASSIC HOUSE (J) ===
  J: {
    name: "Jurassic House",
    code: "J",
    lat: 50.7426,
    lng: -1.8890,
    northOffset: 0,
    floors: {
      G: {
        name: "Ground Floor",
        waypoints: [
          { id: "JG-ENTRANCE", x: 0, y: 0, label: "Main Entrance", isEntrance: true },
          { id: "JG-CORR1", x: 8, y: 0, label: "Main Corridor" },
          { id: "JG-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "J1-STAIRS1" } },
        ],
        edges: [
          { from: "JG-ENTRANCE", to: "JG-CORR1", distance: 8 },
          { from: "JG-CORR1", to: "JG-STAIRS1", distance: 7 },
        ],
        rooms: [],
      },
      1: {
        name: "First Floor",
        waypoints: [
          { id: "J1-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "JG-STAIRS1" } },
          { id: "J1-CORR1", x: 8, y: 0, label: "Main Corridor" },
        ],
        edges: [
          { from: "J1-STAIRS1", to: "J1-CORR1", distance: 7 },
        ],
        rooms: [],
      },
    },
  },

  // === STUDENT CENTRE (SC) ===
  SC: {
    name: "Student Centre",
    code: "SC",
    lat: 50.7420,
    lng: -1.8935,
    northOffset: 0,
    floors: {
      G: {
        name: "Ground Floor",
        waypoints: [
          { id: "SCG-ENTRANCE", x: 0, y: 0, label: "Main Entrance", isEntrance: true },
          { id: "SCG-CORR1", x: 8, y: 0, label: "Main Corridor" },
          { id: "SCG-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "SC1-STAIRS1" } },
        ],
        edges: [
          { from: "SCG-ENTRANCE", to: "SCG-CORR1", distance: 8 },
          { from: "SCG-CORR1", to: "SCG-STAIRS1", distance: 7 },
        ],
        rooms: [],
      },
      1: {
        name: "First Floor",
        waypoints: [
          { id: "SC1-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "SCG-STAIRS1" } },
          { id: "SC1-CORR1", x: 8, y: 0, label: "Main Corridor" },
        ],
        edges: [
          { from: "SC1-STAIRS1", to: "SC1-CORR1", distance: 7 },
        ],
        rooms: [],
      },
    },
  },

  // === SIR MICHAEL COBHAM LIBRARY (DL) ===
  DL: {
    name: "Sir Michael Cobham Library",
    code: "DL",
    lat: 50.7416,
    lng: -1.8932,
    northOffset: 0,
    floors: {
      G: {
        name: "Ground Floor",
        waypoints: [
          { id: "DLG-ENTRANCE", x: 0, y: 0, label: "Main Entrance", isEntrance: true },
          { id: "DLG-CORR1", x: 8, y: 0, label: "Main Corridor" },
          { id: "DLG-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "DL1-STAIRS1" } },
        ],
        edges: [
          { from: "DLG-ENTRANCE", to: "DLG-CORR1", distance: 8 },
          { from: "DLG-CORR1", to: "DLG-STAIRS1", distance: 7 },
        ],
        rooms: [],
      },
      1: {
        name: "First Floor",
        waypoints: [
          { id: "DL1-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "DLG-STAIRS1" } },
          { id: "DL1-CORR1", x: 8, y: 0, label: "Main Corridor" },
        ],
        edges: [
          { from: "DL1-STAIRS1", to: "DL1-CORR1", distance: 7 },
        ],
        rooms: [],
      },
    },
  },

  // === TOLPUDDLE ANNEX (TA) ===
  TA: {
    name: "Tolpuddle Annex",
    code: "TA",
    lat: 50.7414,
    lng: -1.8905,
    northOffset: 0,
    floors: {
      G: {
        name: "Ground Floor",
        waypoints: [
          { id: "TAG-ENTRANCE", x: 0, y: 0, label: "Main Entrance", isEntrance: true },
          { id: "TAG-CORR1", x: 8, y: 0, label: "Main Corridor" },
          { id: "TAG-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "TA1-STAIRS1" } },
        ],
        edges: [
          { from: "TAG-ENTRANCE", to: "TAG-CORR1", distance: 8 },
          { from: "TAG-CORR1", to: "TAG-STAIRS1", distance: 7 },
        ],
        rooms: [],
      },
      1: {
        name: "First Floor",
        waypoints: [
          { id: "TA1-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "TAG-STAIRS1" } },
          { id: "TA1-CORR1", x: 8, y: 0, label: "Main Corridor" },
        ],
        edges: [
          { from: "TA1-STAIRS1", to: "TA1-CORR1", distance: 7 },
        ],
        rooms: [],
      },
    },
  },

  // === POOLE GATEWAY BUILDING (PB) ===
  // Note: Map says "PG" but we use "PB" to avoid conflict with
  // Poole House room codes (PG22 = Poole House, Ground, Room 22).
  // Room codes: PBG01, PB101, etc.
  PB: {
    name: "Poole Gateway Building",
    code: "PB",
    lat: 50.7416,
    lng: -1.8880,
    northOffset: 0,
    floors: {
      G: {
        name: "Ground Floor",
        waypoints: [
          { id: "PBG-ENTRANCE", x: 0, y: 0, label: "Main Entrance", isEntrance: true },
          { id: "PBG-CORR1", x: 8, y: 0, label: "Main Corridor" },
          { id: "PBG-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "PB1-STAIRS1" } },
        ],
        edges: [
          { from: "PBG-ENTRANCE", to: "PBG-CORR1", distance: 8 },
          { from: "PBG-CORR1", to: "PBG-STAIRS1", distance: 7 },
        ],
        rooms: [],
      },
      1: {
        name: "First Floor",
        waypoints: [
          { id: "PB1-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "PBG-STAIRS1" } },
          { id: "PB1-CORR1", x: 8, y: 0, label: "Main Corridor" },
        ],
        edges: [
          { from: "PB1-STAIRS1", to: "PB1-CORR1", distance: 7 },
        ],
        rooms: [],
      },
    },
  },

  // === TALBOT HOUSE (T) ===
  T: {
    name: "Talbot House",
    code: "T",
    lat: 50.7404,
    lng: -1.8905,
    northOffset: 0,
    floors: {
      G: {
        name: "Ground Floor",
        waypoints: [
          { id: "TG-ENTRANCE", x: 0, y: 0, label: "Main Entrance", isEntrance: true },
          { id: "TG-CORR1", x: 8, y: 0, label: "Main Corridor" },
          { id: "TG-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "1", waypointId: "T1-STAIRS1" } },
        ],
        edges: [
          { from: "TG-ENTRANCE", to: "TG-CORR1", distance: 8 },
          { from: "TG-CORR1", to: "TG-STAIRS1", distance: 7 },
        ],
        rooms: [],
      },
      1: {
        name: "First Floor",
        waypoints: [
          { id: "T1-STAIRS1", x: 15, y: 0, label: "Stairwell", isStairs: true, connectsTo: { floor: "G", waypointId: "TG-STAIRS1" } },
          { id: "T1-CORR1", x: 8, y: 0, label: "Main Corridor" },
        ],
        edges: [
          { from: "T1-STAIRS1", to: "T1-CORR1", distance: 7 },
        ],
        rooms: [],
      },
    },
  },
};
